import type { Metadata, Viewport } from "next";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";

const SITE_URL = "https://runbar.run";
const TITLE = "RunBar — a runner in your menu bar";
const DESCRIPTION =
  "Mac menu-bar app for runners. A tiny figure runs toward your weekly finish line. Strava-synced. macOS 14+. Free.";
const TAGLINE =
  "Strava tells you what you did. RunBar tells you where you stand — right now.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: TITLE,
    template: "%s · RunBar",
  },
  description: DESCRIPTION,
  applicationName: "RunBar",
  authors: [{ name: "Rod" }],
  keywords: [
    "macOS menu bar app",
    "Strava",
    "running",
    "weekly goal",
    "Mac app",
    "menu bar",
    "runner",
    "fitness tracker",
  ],
  alternates: {
    canonical: SITE_URL,
  },
  // openGraph & twitter image are generated by app/opengraph-image.tsx —
  // Next.js auto-injects the right meta tags. We leave the rest of the
  // openGraph config explicit so we control title/description/locale.
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: "RunBar",
    title: TITLE,
    description: TAGLINE,
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: TAGLINE,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  category: "productivity",
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fbf9f4" },
    { media: "(prefers-color-scheme: dark)", color: "#0f0f0e" },
  ],
  width: "device-width",
  initialScale: 1,
};

// JSON-LD structured data — schema.org SoftwareApplication.
// Helps Google index RunBar with rich result formatting.
const jsonLd = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "RunBar",
  description: DESCRIPTION,
  applicationCategory: "HealthApplication",
  operatingSystem: "macOS 14",
  url: SITE_URL,
  downloadUrl: `${SITE_URL}/download/RunBar.dmg`,
  softwareVersion: "0.1.22",
  fileSize: "2.4 MB",
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
  },
  author: {
    "@type": "Person",
    name: "Rod",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="bg-ivory text-ink">
        {children}
        <Analytics />
      </body>
    </html>
  );
}
